name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v1
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - name: build
      run: |
        npm ci
        npm run build
    - name: deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
